version: "3.6"

services:

  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    container_name: kafka

  spark:
    build:
      context: ./StreamProcessor
      dockerfile: Dockerfile
    container_name: spark

  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: mongodb

  finnhubproducer:
    build:
      context: ./finnhub_producer
      dockerfile: Dockerfile
    container_name: FinnhubProducer